### ISSUE TITLE
Scraper does not work, gives error.

### ISSUE THREAD

**Issue by Behem07h** [shubham418/yiff_scraper#7] opened 2019-12-26 12:52 UTC
When running yiff scraper, it gives the following error:
*Starting project 103382
Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 84, in download_and_save_all
    if name_element not in os.listdir():
TypeError: listdir() takes exactly 1 argument (0 given)

Steps to reproduce:
1. in command prompt, navigate to directory that yiff_scraper.py is in.
2. run the command "python yiff_scraper.py {link} (i used https://yiff.party/patreon/103382)

I am using python 3.5 and have installed the necessary dependencies

**Comment by anycorn** [comment] 2019-12-26 18:37
I think below python 3.6 the os.listdir() function might not default to current working directory. Try os.listdir(".") as a quick fix?

**Comment by Behem07h** [comment] 2019-12-27 04:12
After changing all "os.listdir()" in the program to "os.listdir(".")" (there were 3 of them), It ran but gave a different error:
Downloading 814e201bb34e0c73be7a67e1cdcf1eefc08d23f3.jpg
Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 94, in download_and_save_all
    save_file(file_path)
  File "yiff_scraper.py", line 64, in save_file
    in_file = requests.get(URL, stream=True)
  File "C:\CASE\Python27\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\CASE\Python27\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\CASE\Python27\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\CASE\Python27\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\CASE\Python27\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yiff.partypatreon', port=443): Max retries exceeded with url: /patreon_inline/32469334/814e201bb34e0c73be7a67e1cdcf1eefc08d23f3.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x045BFE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by anycorn** [comment] 2019-12-30 01:10
You might be executing it with Python 2.7 instead of Python 3 ^^;. If you're on Linux try /usr/bin/python3 or /usr/bin/python3.6 or similar

*EDIT* Please also make sure you've installed the dependencies for the python 3 install you want to use, not python 2!

**Comment by Behem07h** [comment] 2019-12-30 01:30
im on a windows computer and only have py 3.5 installed

**Comment by anycorn** [comment] 2020-01-11 15:14
In this case python -V gives you the version still^^

**Comment by benaiu** [comment] 2020-04-22 18:45
> You might be executing it with Python 2.7 instead of Python 3 ^^;. If you're on Linux try /usr/bin/python3 or /usr/bin/python3.6 or similar
> 
> _EDIT_ Please also make sure you've installed the dependencies for the python 3 install you want to use, not python 2!
same error as OP

manjaro 
python 3.8.2
requests 2.21.0
beautifulsoup4 4.7.1
changed os.listdir() to "os.listdir("."), still same error:
```
Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 85, in download_and_save_all
    os.mkdir(name_element)
TypeError: mkdir: path should be string, bytes or os.PathLike, not NoneType
```
crearly not a python2 vs python3 error

**Comment by shubham418** [comment] 2020-06-17 22:34
Hi can you please try the updated code (wasn't updated in a long time) with lots of changes, might fix your problem. If it doesn't plz send me the link of the page you tried to scrape.

**Comment by shubham418** [comment] 2020-06-18 05:40
Hi, @Behem07h , I tried scraping the page with the new code and could not reproduce the bug, all the pages are being scraped properly. So I'll be closing this issue, reopen if the updated version doesn't work for you. 

Hi, @benaiu could you please try the updated code and see if your still getting the problem (reopen if you are), thanks.

**Closed as completed by shubham418** 2020-06-18 05:40 UTC
