### ISSUE TITLE
Does not create new file name

### ISSUE THREAD

**Issue by prabhavsidhaye** [shubham418/yiff_scraper#5] opened 2019-08-04 17:07 UTC
File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 84, in download_and_save_all
    if name_element not in os.listdir():
TypeError: listdir() takes exactly 1 argument (0 given)

Shows above error

**Comment by shubham418** [comment] 2020-06-17 22:37
Hi can you please try the updated code (wasn't updated in a long time) with lots of changes, might fix your problem. If it doesn't plz send me the link of the page you tried to scrape.

**Comment by shubham418** [comment] 2020-06-18 05:55
Hi @prabhavsidhaye please try the updated code with the newest version of python. I;m closing the issue as I could not reproduce the issue and the newer version might fix it. If it still doesn't work reopen the issue and share the link you were scraping.

**Closed as completed by shubham418** 2020-06-18 05:55 UTC
