### ISSUE TITLE
decryption failed

### ISSUE THREAD

**Issue by wankio** [shubham418/yiff_scraper#3] opened 2019-04-23 09:01 UTC
*Starting project 4575047
WARNING: Folder for same already exists. Please delete and try again.

Downloading ezgifcom-optimize_9(1).gif

ezgifcom-optimize_9(1).gif Complete

Downloading Samus%20anal%20fucked%201080p.mp4
Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 94, in download_and_save_all
    save_file(file_path)
  File "yiff_scraper.py", line 66, in save_file
    for chunk in in_file.iter_content(chunk_size=8192):
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2471)

**Comment by shubham418** [comment] 2020-06-17 22:39
Hi can you please try the updated code (wasn't updated in a long time) with lots of changes, might fix your problem. If it doesn't plz send me the link of the page you tried to scrape.

Also my previous code didn't support updating a project, so if you had partially downloaded it and tried again, might be a problem.

**Comment by shubham418** [comment] 2020-06-18 05:50
Hi @wankio ,

I tried `python .\yiff_scraper.py https://yiff.party/patreon/4575047` (assuming Archoangel) with the newer updated code and could not reproduce the issue and all pages are being scraped and downloaded properly. Please try the updated code, I'm closing this issue, but reopen if it still doesn't work.

**Closed as completed by shubham418** 2020-06-18 05:50 UTC
