### ISSUE TITLE
Gives error, not working

### ISSUE THREAD

**Issue by Adarsh777** [shubham418/yiff_scraper#8] opened 2020-02-21 05:29 UTC
Hello,

I'm getting this error while running command python yiff_scraper.py link here

*Starting project 22060390
Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 85, in download_and_save_all
    os.mkdir(name_element)
TypeError: mkdir: path should be string, bytes or os.PathLike, not NoneType

**Comment by shubham418** [comment] 2020-06-17 22:33
Hi can you please try the updated code (wasn't updated in a long time) with lots of changes, might fix your problem. If it doesn't plz send me the link of the page you tried to scrape.

**Comment by shubham418** [comment] 2020-06-18 05:46
Hi @Adarsh777 ,

It seems it was an issue where it could not find the name_element from the website. I tried `python .\yiff_scraper.py https://yiff.party/patreon/22060390` (assuming creativemints is who you were scraping) with the new updated code and could not reproduce the bug, please try the updated code.

I'm closing the issue, reopen if it still doesn't work.

**Closed as completed by shubham418** 2020-06-18 05:46 UTC
