### ISSUE TITLE
There're errors on the script

### ISSUE THREAD

**Issue by ghost** [shubham418/yiff_scraper#10] opened 2020-05-25 11:57 UTC
So I used this code to scrap videos on patreon, but it gives me this error. I have tried with the main url from that patreon account and with the url from one of the videos. I have installed all the requirements successfully and I'm using python 3.8.2 

```
Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 79, in download_and_save_all
    response = requests.get(URL)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for {url}
```

**Comment by shubham418** [comment] 2020-06-17 22:31
hi can you please try out the updated version and let me know if your still having the issue.
If you're still having the problem please send me the link of the yiff page.

**Comment by ghost** [comment] 2020-06-17 23:35
Ok I think I downloaded the updated version, because I it has less errors now, but I still have issues:
```
*Starting project kirstypartridge
Traceback (most recent call last):
  File "yiff_scraper.py", line 214, in <module>
    project_links_scraper(project)
  File "yiff_scraper.py", line 178, in project_links_scraper
    name_element = soup.find_all("span", {"class": "yp-info-name"})[0].text
IndexError: list index out of range
```
I want to scrape videos from this page https://www.patreon.com/kirstypartridge, I mean I want to subscribe, but my country is still in a lockdown bc of COVID and I can't recharge my debit card. Maybe that's the actual issue? I don't know.

**Comment by shubham418** [comment] 2020-06-18 05:26
Hi, This is a tool to scrape content off https://yiff.party which is a website where content from patreon is uploaded ("not so legally"). You can go and search for "kirstypartridge" on the website and you'll find her page with most ("not all as some stuff doesn't get uploaded [you can help the website out with that]"). Your error is because your scraping the wrong website. I searched on your behalf and found the page on yiff.party and the scraper works as intended. Use the following command:
`python .\yiff_scraper.py https://yiff.party/patreon/5714818`
The content will be downloaded to './yiff_scraper/Downloads/{Name of patreon}'.

Note: I'm blacklisting archive files from downloading, this can be changed inside the file but you'll have to search for it a bit.

I'm closing this issue as there doesn't seem to be a problem with the tool.

**Closed as completed by shubham418** 2020-06-18 05:26 UTC

**Comment by ghost** [comment] 2020-06-18 14:40
Ok thank you, I wasn't aware of that page.
